# Generated by Django 4.2.11 on 2024-05-18 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('image_url', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('sku', models.CharField(db_index=True, max_length=50)),
            ],
            options={
                'db_table': 'images',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('sku', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('product_url', models.CharField(max_length=255)),
                ('product_title', models.CharField(max_length=255)),
                ('normal_price', models.CharField(max_length=50)),
                ('discount_price', models.CharField(max_length=50)),
                ('stock', models.CharField(max_length=50)),
                ('categories', models.CharField(max_length=255)),
                ('subcategories', models.CharField(max_length=255)),
                ('breadcrumb', models.CharField(max_length=255)),
                ('weight', models.CharField(max_length=50)),
                ('dimension', models.CharField(max_length=255)),
                ('height', models.CharField(max_length=50)),
                ('width', models.CharField(max_length=50)),
                ('length', models.CharField(max_length=50)),
                ('approximate_weight', models.CharField(max_length=50)),
                ('descriptions', models.TextField()),
                ('short_description', models.TextField()),
                ('LastScrappeddate', models.DateTimeField(auto_now=True)),
                ('Updateddate', models.DateTimeField(auto_now=True)),
                ('Createddate', models.DateTimeField(auto_now_add=True)),
                ('Status', models.CharField(max_length=50)),
                ('main_image_url', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'products',
            },
        ),
    ]
